### ISSUE TITLE
Allow for custom SnakeYAML construction.

### ISSUE THREAD

**Issue by garretwilson** [sbaudoin/yamllint#20]
I think we're close to getting your YAML linter library working for our project. I see that it lints in two steps: syntax errors using SnakeYAML, and then "cosmetic" problems using its own list of rules.

I think it's great that it uses SnakeYAML. In fact our project uses SnakeYAML as well. However we have certain constructs that SnakeYAML would flag as an error, so we use the `YAML(BaseConstructor)` constructor to configure it to recognize these things.

Unfortunately the linter just creates a SnakeYAML instance using `new YAML()`, so the linter thinks some of our files have syntax errors. Is there any way you could expose the SnakeYAML construction somehow so that we can customize it? Or just allowing us to pass our own configured SnakeYAML `YAML` instance would probably suffice.

Otherwise, as a workaround we'll have to extract the main linting code and modify it so that we perform the syntax checking with the custom-configured SnakeYAML `YAML` instance before calling the duplicated linter code for "cosmetic" checks.

**Comment by sbaudoin** [comment]
Hello,

Can you detail how you use yamllint, please? If you use the API, can you give a code sample that shows how you would like the linter to accept constructors?

Thanks

**Comment by garretwilson** [comment]
If I just create a reasonable pull request that allows passing a `BaseConstructor` so that the user of your library can configure the SnakeYAML instance you create, would you accept such a pull request? Do you know how long it would take for you to accept it and create a new version? I'll gladly contribute, but we have a big project that doesn't have time for a long wait. If it would take a while, I would have to just extract your code and modify it in our application as I mentioned.

**Comment by sbaudoin** [comment]
Yes, please, proceed with the PR. I'm working on the improvements from your other issue, so my plan is not to take long to release a new version.

**Comment by garretwilson** [comment]
Great; let me check with the project manager to see if that works with our schedule. I'll try to get back to you today.

**Comment by garretwilson** [comment]
I'm about ready to start working on this. Since https://github.com/sbaudoin/yamllint/issues/19 changes some of the methods that I will be working with, so maybe I should wait until you finish and merge https://github.com/sbaudoin/yamllint/pull/21 ?

**Comment by sbaudoin** [comment]
I expected so. Just as you wish.

**Comment by garretwilson** [comment]
OK; well just let me know if I can help on anything else to get https://github.com/sbaudoin/yamllint/pull/21 done. I've already forked the repository and I'm ready to address this ticket immediately.

**Comment by sbaudoin** [comment]
Done

**Comment by garretwilson** [comment]
@sbaudoin I think the changes are ready for review.

**Comment by garretwilson** [comment]
Good morning, @sbaudoin . Thank you for accepting and merging my pull request. Do you need anything further from me before we get a new version released?

**Comment by sbaudoin** [comment]
Hello,

No, thanks a lot. I plan to release the new version by the end of the week (sunday).
