### ISSUE TITLE
Consider using ServiceLoader facilities instead of Reflections

### ISSUE THREAD

**Issue by aalmiray** [sbaudoin/yamllint#39]
I think it would be better to use the standard https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html facilities than relying on reflection to lookup all instances of a type `Rule` available on the classpath. Services may be registered manually at `/META-inf/services/com.github.sbaudoin.yamllint.rules.Rule` or via annotation processors such as Google's AutoService (https://github.com/google/auto/tree/master/service) or Jipsy (https://github.com/kordamp/jipsy).

I can setup a PR with manual setup or with any of those APTs if you agree.

**Comment by aalmiray** [comment]
See https://github.com/jreleaser/jreleaser/commit/ab54c567ff0a899a7add0ddaf330862590eb507e for one possible option (using the manual approach to list entries in `/META-inf/services/com.github.sbaudoin.yamllint.rules.Rule`)

**Comment by sbaudoin** [comment]
Hello,

That looks interesting. So yes, you may try to push a PR.

**Comment by aalmiray** [comment]
Would you like to keep the list of rules manually or do you prefer to use an annotation processor to do the job?
