### ISSUE TITLE
Add min-spaces-after to hyphen rule

### ISSUE THREAD

**Issue by mikebell90** [sbaudoin/yamllint#52]
Use case

```
foo:
     -broken
```
vs 
```
foo:
    - correct
```

**Comment by sbaudoin** [comment]
Hello. Your example does not make much sense. As per [the YAML 1.1 spec](https://yaml.org/spec/1.1/#block%20sequence%20style/information%20model), "Block sequences indicate each entry with a dash and space". If you do not put a space then you have a scalar. I may implement such a rule but the supported min space value would be 1, not 0. Any thought?

**Comment by mikebell90** [comment]
Exactly. It's not valid yaml. But users have entered it before and we'd like to catch it. Exactly how implementation wise is certainly your choice

**Comment by sbaudoin** [comment]
The problem is that the parser will identify "-x" as a scalar. In such a case I may check if this scalar starts with an hyphen but what it this is a valid, expected scalar starting with an hyphen? I cannot guess and make the difference...

**Comment by sbaudoin** [comment]
So if you could have a look at #59
